version: '2'
services:
    web:
        build: .
        command: bash -c "while ! nc -z db 5432; do sleep 1; done;
            python manage.py migrate && 
            python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
        links:
            - db
    db:
        image: postgres
        environment:
            POSTGRES_USER: dbuser
            POSTGRES_PASSWORD: password 
            POSTGRES_DB: depsDB


